---
title: "Introducción al procesamiento, visualización y mapeo de datos biologicos"
description: |
  Este curso proporciona capacitación en el procesamiento, visualización y mapeo de datos biologicos utilizando R.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

## Estructura del curso

Este es un curso de dos dias

### Día 1
Introducción al análisis de datos en R. Tipos de objetos en R. Visualización para comprobar errores y patrones en los datos (ggplot) Preparación de tablas para la generación de análisis espaciales (dplyr – tidyr)

### Día 2
Importación y visualización de datos espaciales (ps, sf, raster, rgdal). Generación de mapas (raster, ggmap, leaflet)

### Datos
Los datos requridos para completar el curso pueden ser descargados de la carpeta Datos_Curso_R_SCMas.zip

### Requisitos
Computador con acceso a internet. Contar con R y RStudio previamente instalados. La instalación del programa no se explicará durante el curso.

La experiencia requerida en R es mínima, sin embargo, se espera que los participantes estén familiarizados con el siguiente tipo de objetos básicos R: vectores, listas y dataframes. 
Puedes ver aprender o repasar el manejo básico de R en [éste tutorial](https://dlizcano.github.io/IntroR)

Para el segundo día, un conocimiento básico sobre conceptos relacionados con sistemas de coordenadas y proyecciones geográficas será ventajoso, aunque no esencial.




